"""
Legacy upload models with backward compatibility adapters.

This module maintains backward compatibility with the old in-memory upload models
while providing adapters to the new database-backed models in extraction.py.

DEPRECATED: Use models from extraction.py for new code.
This module is maintained for API backward compatibility only.

Requirements: 19.2, 19.6, 19.7
"""
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from datetime import datetime, date
from uuid import UUID
from decimal import Decimal

# Import new database models
from app.models.extraction import (
    ExtractionJob as DBExtractionJob,
    ExtractionPage as DBExtractionPage,
    ExtractionBlock as DBExtractionBlock,
    RawQuestion as DBRawQuestion,
    ExtractionStage,
    ProcessingStatus
)


# ============================================================================
# Legacy Models (Deprecated - for backward compatibility only)
# ============================================================================

class ExtractedQuestion(BaseModel):
    """Legacy extracted question model for backward compatibility."""
    question_number: int
    question_text: str
    options: List[Dict[str, str]]  # [{"id": "A", "text": "..."}, ...]
    confidence: float  # OCR confidence score
    subject: Optional[str] = None
    topic: Optional[str] = None

    @classmethod
    def from_db_raw_question(cls, db_raw_question: DBRawQuestion, confidence: float = 0.9) -> 'ExtractedQuestion':
        """
        Convert database RawQuestion to legacy ExtractedQuestion format.
        
        Args:
            db_raw_question: Database raw question model
            confidence: OCR confidence score (default 0.9)
        
        Returns:
            Legacy ExtractedQuestion instance
        """
        # Convert options list to legacy format with IDs
        options = []
        for idx, option_text in enumerate(db_raw_question.options):
            options.append({
                "id": chr(65 + idx),  # A, B, C, D, ...
                "text": option_text
            })
        
        # Parse question number to int (handle formats like "1", "2a", "Q5")
        try:
            question_num = int(''.join(filter(str.isdigit, db_raw_question.question_number)))
        except (ValueError, TypeError):
            question_num = 0
        
        return cls(
            question_number=question_num,
            question_text=db_raw_question.question_text,
            options=options,
            confidence=confidence,
            subject=db_raw_question.chapter_context,  # Using chapter_context as subject
            topic=db_raw_question.topic_context
        )

    def to_db_raw_question(self, job_id: UUID, page_number: Optional[int] = None) -> DBRawQuestion:
        """
        Convert legacy ExtractedQuestion to database RawQuestion format.
        
        Args:
            job_id: Extraction job ID
            page_number: Optional page number
        
        Returns:
            Database RawQuestion instance
        """
        # Convert options to simple list of strings
        options_list = [opt["text"] for opt in self.options]
        
        return DBRawQuestion(
            id=UUID(int=0),  # Will be generated by database
            job_id=job_id,
            question_number=str(self.question_number),
            question_text=self.question_text,
            options=options_list,
            page_number=page_number,
            chapter_context=self.subject,
            topic_context=self.topic,
            sub_topic_context=None,
            raw_images=None,
            raw_tables=None,
            processing_status=ProcessingStatus.PENDING,
            error_message=None,
            question_id=None,
            created_at=datetime.utcnow()
        )


class UploadResponse(BaseModel):
    """Legacy upload response model for backward compatibility."""
    id: str
    status: str  # 'pending', 'processing', 'completed', 'failed'
    message: str
    uploaded_at: datetime

    @classmethod
    def from_db_extraction_job(cls, db_job: DBExtractionJob, message: str = "Upload successful") -> 'UploadResponse':
        """
        Convert database ExtractionJob to legacy UploadResponse format.
        
        Args:
            db_job: Database extraction job model
            message: Response message
        
        Returns:
            Legacy UploadResponse instance
        """
        # Map ExtractionStage to legacy status
        status_mapping = {
            ExtractionStage.QUEUED: "pending",
            ExtractionStage.VALIDATION: "processing",
            ExtractionStage.UPLOAD: "processing",
            ExtractionStage.EXTRACTION: "processing",
            ExtractionStage.COMPLETED: "completed",
            ExtractionStage.FAILED: "failed"
        }
        
        return cls(
            id=str(db_job.id),
            status=status_mapping.get(db_job.stage, "pending"),
            message=message,
            uploaded_at=db_job.created_at
        )


class UploadedTest(BaseModel):
    """Legacy uploaded test model for backward compatibility."""
    id: str
    user_id: str
    test_image_url: str
    response_image_url: Optional[str] = None
    extracted_questions: List[ExtractedQuestion]
    processing_status: str
    error_message: Optional[str] = None
    uploaded_at: datetime
    processed_at: Optional[datetime] = None
    exam_type: Optional[str] = None
    exam_date: Optional[date] = None
    exam_session: Optional[str] = None

    @classmethod
    def from_db_extraction_job(
        cls,
        db_job: DBExtractionJob,
        user_id: str,
        test_image_url: str,
        raw_questions: Optional[List[DBRawQuestion]] = None,
        response_image_url: Optional[str] = None,
        exam_type: Optional[str] = None,
        exam_date: Optional[date] = None,
        exam_session: Optional[str] = None
    ) -> 'UploadedTest':
        """
        Convert database ExtractionJob and RawQuestions to legacy UploadedTest format.
        
        Args:
            db_job: Database extraction job model
            user_id: User ID who uploaded the test
            test_image_url: URL to the uploaded test image/PDF
            raw_questions: List of database raw questions (if available)
            response_image_url: Optional URL to response sheet
            exam_type: Optional exam type
            exam_date: Optional exam date
            exam_session: Optional exam session
        
        Returns:
            Legacy UploadedTest instance
        """
        # Map ExtractionStage to legacy processing_status
        status_mapping = {
            ExtractionStage.QUEUED: "pending",
            ExtractionStage.VALIDATION: "processing",
            ExtractionStage.UPLOAD: "processing",
            ExtractionStage.EXTRACTION: "processing",
            ExtractionStage.COMPLETED: "completed",
            ExtractionStage.FAILED: "failed"
        }
        
        # Convert raw questions to legacy format
        extracted_questions = []
        if raw_questions:
            extracted_questions = [
                ExtractedQuestion.from_db_raw_question(rq)
                for rq in raw_questions
            ]
        
        return cls(
            id=str(db_job.id),
            user_id=user_id,
            test_image_url=test_image_url,
            response_image_url=response_image_url,
            extracted_questions=extracted_questions,
            processing_status=status_mapping.get(db_job.stage, "pending"),
            error_message=db_job.error,
            uploaded_at=db_job.created_at,
            processed_at=db_job.completed_at,
            exam_type=exam_type,
            exam_date=exam_date,
            exam_session=exam_session
        )


class QuestionConfirmRequest(BaseModel):
    """Request model for confirming extracted questions."""
    upload_id: str
    questions: List[Dict[str, Any]]  # Confirmed/edited questions
    user_answers: Optional[Dict[int, str]] = None  # Question number -> selected answer


class UploadStatusResponse(BaseModel):
    """Legacy upload status response model for backward compatibility."""
    id: str
    status: str
    progress: int  # 0-100
    extracted_questions: Optional[List[ExtractedQuestion]] = None
    error_message: Optional[str] = None

    @classmethod
    def from_db_extraction_job(
        cls,
        db_job: DBExtractionJob,
        raw_questions: Optional[List[DBRawQuestion]] = None
    ) -> 'UploadStatusResponse':
        """
        Convert database ExtractionJob to legacy UploadStatusResponse format.
        
        Args:
            db_job: Database extraction job model
            raw_questions: Optional list of database raw questions
        
        Returns:
            Legacy UploadStatusResponse instance
        """
        # Map ExtractionStage to legacy status
        status_mapping = {
            ExtractionStage.QUEUED: "pending",
            ExtractionStage.VALIDATION: "processing",
            ExtractionStage.UPLOAD: "processing",
            ExtractionStage.EXTRACTION: "processing",
            ExtractionStage.COMPLETED: "completed",
            ExtractionStage.FAILED: "failed"
        }
        
        # Convert progress (Decimal 0-100) to int
        progress = int(db_job.progress)
        
        # Convert raw questions to legacy format if available
        extracted_questions = None
        if raw_questions and db_job.stage == ExtractionStage.COMPLETED:
            extracted_questions = [
                ExtractedQuestion.from_db_raw_question(rq)
                for rq in raw_questions
            ]
        
        return cls(
            id=str(db_job.id),
            status=status_mapping.get(db_job.stage, "pending"),
            progress=progress,
            extracted_questions=extracted_questions,
            error_message=db_job.error
        )


# ============================================================================
# Backward Compatibility Helper Functions
# ============================================================================

def convert_extraction_job_to_upload_response(
    db_job: DBExtractionJob,
    message: str = "Upload successful"
) -> Dict[str, Any]:
    """
    Convert database ExtractionJob to legacy UploadResponse API format.
    
    This function ensures API backward compatibility by converting
    new database models to the format expected by existing API clients.
    
    Args:
        db_job: Database extraction job model
        message: Response message
    
    Returns:
        Dictionary in legacy API format
    """
    legacy_response = UploadResponse.from_db_extraction_job(db_job, message)
    return legacy_response.model_dump()


def convert_extraction_job_to_upload_status(
    db_job: DBExtractionJob,
    raw_questions: Optional[List[DBRawQuestion]] = None
) -> Dict[str, Any]:
    """
    Convert database ExtractionJob to legacy UploadStatusResponse API format.
    
    Args:
        db_job: Database extraction job model
        raw_questions: Optional list of database raw questions
    
    Returns:
        Dictionary in legacy API format
    """
    legacy_status = UploadStatusResponse.from_db_extraction_job(db_job, raw_questions)
    return legacy_status.model_dump()


def convert_extraction_job_to_uploaded_test(
    db_job: DBExtractionJob,
    user_id: str,
    test_image_url: str,
    raw_questions: Optional[List[DBRawQuestion]] = None,
    response_image_url: Optional[str] = None,
    exam_type: Optional[str] = None,
    exam_date: Optional[date] = None,
    exam_session: Optional[str] = None
) -> Dict[str, Any]:
    """
    Convert database ExtractionJob to legacy UploadedTest API format.
    
    Args:
        db_job: Database extraction job model
        user_id: User ID who uploaded the test
        test_image_url: URL to the uploaded test image/PDF
        raw_questions: Optional list of database raw questions
        response_image_url: Optional URL to response sheet
        exam_type: Optional exam type
        exam_date: Optional exam date
        exam_session: Optional exam session
    
    Returns:
        Dictionary in legacy API format
    """
    legacy_test = UploadedTest.from_db_extraction_job(
        db_job,
        user_id,
        test_image_url,
        raw_questions,
        response_image_url,
        exam_type,
        exam_date,
        exam_session
    )
    return legacy_test.model_dump()


def convert_raw_question_to_extracted_question(
    db_raw_question: DBRawQuestion,
    confidence: float = 0.9
) -> Dict[str, Any]:
    """
    Convert database RawQuestion to legacy ExtractedQuestion API format.
    
    Args:
        db_raw_question: Database raw question model
        confidence: OCR confidence score (default 0.9)
    
    Returns:
        Dictionary in legacy API format
    """
    legacy_question = ExtractedQuestion.from_db_raw_question(db_raw_question, confidence)
    return legacy_question.model_dump()


def convert_extracted_question_to_raw_question(
    extracted_question: ExtractedQuestion,
    job_id: UUID,
    page_number: Optional[int] = None
) -> DBRawQuestion:
    """
    Convert legacy ExtractedQuestion to database RawQuestion format.
    
    Args:
        extracted_question: Legacy extracted question model
        job_id: Extraction job ID
        page_number: Optional page number
    
    Returns:
        Database RawQuestion instance
    """
    return extracted_question.to_db_raw_question(job_id, page_number)


def get_legacy_status_from_stage(stage: ExtractionStage) -> str:
    """
    Map ExtractionStage enum to legacy status string.
    
    Args:
        stage: ExtractionStage enum value
    
    Returns:
        Legacy status string ('pending', 'processing', 'completed', 'failed')
    """
    status_mapping = {
        ExtractionStage.QUEUED: "pending",
        ExtractionStage.VALIDATION: "processing",
        ExtractionStage.UPLOAD: "processing",
        ExtractionStage.EXTRACTION: "processing",
        ExtractionStage.COMPLETED: "completed",
        ExtractionStage.FAILED: "failed"
    }
    return status_mapping.get(stage, "pending")


def get_stage_from_legacy_status(status: str) -> ExtractionStage:
    """
    Map legacy status string to ExtractionStage enum.
    
    Args:
        status: Legacy status string
    
    Returns:
        ExtractionStage enum value
    """
    status_mapping = {
        "pending": ExtractionStage.QUEUED,
        "processing": ExtractionStage.EXTRACTION,
        "completed": ExtractionStage.COMPLETED,
        "failed": ExtractionStage.FAILED
    }
    return status_mapping.get(status, ExtractionStage.QUEUED)
