"""
API endpoints for PDF processing and question extraction.

This module provides RESTful endpoints for uploading PDFs, tracking processing status,
retrieving results, and validating PDF structure before processing.

For local development, extracted markdown, images, and the manifest are stored
under the backend data folder so the full flow can be tested without Supabase.
"""

from fastapi import APIRouter, UploadFile, File, Form, HTTPException, status, BackgroundTasks
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from pathlib import Path
import uuid
from datetime import datetime, timezone

from app.services.pdf_extraction.document_processor import DocumentProcessor
from app.services.pdf_extraction.models import BookMetadata


router = APIRouter(prefix="/api/pdf", tags=["pdf-processing"])
BACKEND_ROOT = Path(__file__).resolve().parents[2]
DATA_ROOT = BACKEND_ROOT / "data"

# Initialize document processor lazily so local extraction can run even when
# unrelated integrations (for example Supabase) are not configured.
processor: Optional[DocumentProcessor] = None


def get_processor() -> DocumentProcessor:
    global processor
    if processor is None:
        try:
            processor = DocumentProcessor()
        except Exception as exc:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail=(
                    "PDF extraction is not configured. "
                    f"Set SARVAM_API_KEY and install backend dependencies. Details: {exc}"
                ),
            ) from exc
    return processor


# Response Models
class UploadResponse(BaseModel):
    """Response for PDF upload endpoint"""
    job_id: str = Field(..., description="Unique job identifier for tracking")
    status: str = Field(..., description="Initial status, usually 'queued'")
    message: str = Field(..., description="Human-readable status message")
    uploaded_at: datetime = Field(..., description="Upload timestamp")


class StatusResponse(BaseModel):
    """Response for status check endpoint"""
    job_id: str = Field(..., description="Job identifier")
    status: str = Field(..., description="Current processing stage")
    progress: float = Field(..., ge=0.0, le=100.0, description="Progress percentage")
    current_stage: str = Field(..., description="Current processing stage")
    is_complete: bool = Field(..., description="Whether processing is complete")
    error: Optional[str] = Field(None, description="Error message if failed")
    current_chapter: Optional[str] = Field(None, description="Current chapter being processed")
    current_topic: Optional[str] = Field(None, description="Current topic being processed")
    questions_extracted: int = Field(..., description="Number of questions extracted so far")


class ResultStatistics(BaseModel):
    """Statistics about extraction results"""
    markdown_file_count: int = Field(..., description="Number of extracted markdown files")
    image_file_count: int = Field(..., description="Number of extracted image files")
    other_file_count: int = Field(..., description="Number of additional extracted files")
    processing_time_seconds: float = Field(..., description="Total processing time in seconds")


class ResultArtifacts(BaseModel):
    """Local artifacts generated by extraction."""

    source_pdf_path: str = Field(..., description="Absolute path of the uploaded PDF")
    output_dir: str = Field(..., description="Absolute path of the job output directory")
    extracted_path: str = Field(..., description="Absolute path of the extracted content directory")
    manifest_path: str = Field(..., description="Absolute path of the manifest JSON")
    markdown_files: List[str] = Field(default_factory=list, description="Relative markdown files inside output_dir")
    image_files: List[str] = Field(default_factory=list, description="Relative image files inside output_dir")
    other_files: List[str] = Field(default_factory=list, description="Relative additional files inside output_dir")
    preview: Optional[str] = Field(None, description="Preview of extracted markdown")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Book metadata used during extraction")


class ResultResponse(BaseModel):
    """Response for result retrieval endpoint"""
    job_id: str = Field(..., description="Job identifier")
    status: str = Field(..., description="Processing status")
    statistics: Optional[ResultStatistics] = Field(None, description="Extraction statistics")
    artifacts: Optional[ResultArtifacts] = Field(None, description="Local extraction artifacts")
    error: Optional[str] = Field(None, description="Error message if failed")


class ValidationResponse(BaseModel):
    """Response for PDF validation endpoint"""
    is_valid: bool = Field(..., description="Whether PDF structure is valid")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Structure confidence score")
    chapter_count: int = Field(..., description="Number of detected chapters")
    errors: List[str] = Field(default_factory=list, description="Validation errors if any")


# Helper function to save uploaded file
def save_upload_file(upload_file: UploadFile, destination: str) -> None:
    """Save uploaded file to destination path"""
    destination_path = Path(destination)
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    upload_file.file.seek(0)
    with destination_path.open("wb") as buffer:
        content = upload_file.file.read()
        buffer.write(content)


# Background task for processing PDF
def process_pdf_background(job_id: str, pdf_path: str, metadata: BookMetadata) -> None:
    """Background task to process PDF"""
    try:
        get_processor().process_pdf(pdf_path, metadata, job_id=job_id)
    except Exception:
        # Error is already logged and stored in the processor result.
        pass


@router.post("/upload", response_model=UploadResponse, status_code=status.HTTP_202_ACCEPTED)
async def upload_pdf(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(..., description="PDF file to process"),
    title: str = Form(..., description="Book title"),
    subject: str = Form(..., description="Subject: Physics, Chemistry, or Mathematics"),
    grade_level: str = Form(..., description="Grade level (1-12)"),
    publisher: str = Form(..., description="Publisher name"),
    edition: Optional[str] = Form(None, description="Edition information"),
    isbn: Optional[str] = Form(None, description="ISBN number")
):
    """
    Upload a PDF file for question extraction.
    
    This endpoint accepts a PDF file along with metadata and starts an asynchronous
    processing job. Returns a job ID that can be used to track progress and retrieve results.
    
    **File Requirements:**
    - Must be a valid PDF file
    - Maximum size: 100MB
    - Must contain structured educational content
    
    **Processing:**
    - Processing happens asynchronously in the background
    - Use the returned job_id to check status via /api/pdf/status/{job_id}
    - Results can be retrieved via /api/pdf/result/{job_id} when complete
    """
    # Validate file type
    if not file.content_type == "application/pdf":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="File must be a PDF"
        )
    
    # Validate file size (100MB limit)
    file.file.seek(0, 2)  # Seek to end
    file_size = file.file.tell()
    file.file.seek(0)  # Reset to beginning
    
    max_size = 100 * 1024 * 1024  # 100MB
    if file_size > max_size:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File size exceeds maximum limit of 100MB (got {file_size / 1024 / 1024:.2f}MB)"
        )
    
    # Create metadata object
    try:
        metadata = BookMetadata(
            title=title,
            subject=subject,
            grade_level=grade_level,
            publisher=publisher,
            edition=edition,
            isbn=isbn
        )
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid metadata: {str(e)}"
        )
    
    # Generate job ID
    job_id = str(uuid.uuid4())
    get_processor().queue_job(job_id)
    
    # Save uploaded file
    upload_dir = DATA_ROOT / "uploads"
    pdf_path = upload_dir / f"{job_id}.pdf"
    
    try:
        save_upload_file(file, str(pdf_path))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to save uploaded file: {str(e)}"
        )
    
    # Start background processing
    background_tasks.add_task(process_pdf_background, job_id, str(pdf_path), metadata)
    
    return UploadResponse(
        job_id=job_id,
        status="queued",
        message="PDF uploaded successfully and queued for processing",
        uploaded_at=datetime.now(timezone.utc)
    )


@router.get("/status/{job_id}", response_model=StatusResponse)
async def get_processing_status(job_id: str):
    """
    Get the processing status of a PDF extraction job.
    
    Returns the current status, progress percentage, and current processing stage.
    
    **Status Values:**
    - `queued`: Job is waiting to start
    - `validation`: The uploaded PDF is being checked
    - `upload`: The source document is being sent to the extractor
    - `extraction`: Extracted files are being downloaded and stored locally
    - `completed`: Job completed successfully
    - `failed`: Job failed with errors
    
    **Progress:**
    - 0-100: Percentage of completion
    - Progress is updated as the job moves through different stages
    """
    status_info = get_processor().get_processing_status(job_id)
    
    if status_info is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found"
        )
    
    return StatusResponse(
        job_id=job_id,
        status=status_info.current_stage.value,
        progress=status_info.progress,
        current_stage=status_info.current_stage.value,
        is_complete=status_info.is_complete,
        error=status_info.error,
        current_chapter=status_info.current_chapter,
        current_topic=status_info.current_topic,
        questions_extracted=status_info.questions_extracted
    )


@router.get("/result/{job_id}", response_model=ResultResponse)
async def get_processing_result(job_id: str):
    """
    Get the results of a completed PDF extraction job.
    
    Returns statistics about the extraction process and a list of extracted question IDs.
    
    **Note:** This endpoint only returns results for completed jobs.
    For jobs that are still processing, use /api/pdf/status/{job_id} instead.
    """
    result = get_processor().get_result(job_id)
    
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job {job_id} not found or not yet completed"
        )
    
    # Build statistics if job was successful
    statistics = None
    
    artifacts = None
    if result.artifacts:
        artifacts = ResultArtifacts(**result.artifacts.model_dump())

    if result.success and result.artifacts:
        statistics = ResultStatistics(
            markdown_file_count=len(result.artifacts.markdown_files),
            image_file_count=len(result.artifacts.image_files),
            other_file_count=len(result.artifacts.other_files),
            processing_time_seconds=result.processing_time_seconds
        )
    
    return ResultResponse(
        job_id=job_id,
        status="completed" if result.success else "failed",
        statistics=statistics,
        artifacts=artifacts,
        error=result.error if not result.success else None
    )


@router.post("/validate", response_model=ValidationResponse)
async def validate_pdf_structure(
    file: UploadFile = File(..., description="PDF file to validate")
):
    """
    Validate PDF structure before processing.
    
    This endpoint analyzes the PDF structure to determine if it's suitable for
    question extraction. It returns a confidence score and detected chapter count.
    
    **Use this endpoint to:**
    - Check if a PDF is suitable for processing before uploading
    - Get an estimate of the document structure
    - Identify potential issues early
    
    **Validation Criteria:**
    - Structure confidence >= 0.7 is considered valid
    - At least one chapter must be detected
    - PDF must have recognizable structure (chapters, topics, sections)
    """
    # Validate file type
    if not file.content_type == "application/pdf":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="File must be a PDF"
        )
    
    # Save temporary file for validation
    temp_id = str(uuid.uuid4())
    temp_dir = DATA_ROOT / "temp"
    temp_path = temp_dir / f"{temp_id}.pdf"
    
    try:
        save_upload_file(file, str(temp_path))
        
        # Validate structure
        validation_result = get_processor().validate_pdf_structure(str(temp_path))
        
        # Clean up temp file
        if temp_path.exists():
            temp_path.unlink()
        
        return ValidationResponse(
            is_valid=validation_result.is_valid,
            confidence=validation_result.confidence,
            chapter_count=validation_result.chapter_count,
            errors=validation_result.errors
        )
    
    except Exception as e:
        # Clean up temp file on error
        if temp_path.exists():
            temp_path.unlink()
        
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Validation failed: {str(e)}"
        )
