// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Prevent URL-based session detection that might cause reloads
    flowType: 'pkce', // Use PKCE flow for better security and stability
    storageKey: 'supabase.auth.token', // Explicit storage key
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 2, // Throttle realtime events to prevent excessive updates
    },
  },
});